name:  Deploy our project #NAME
# When should we run our action? : EVENT things that happen on the repo cretates a pull request, create branch, push
on: [pull_request]
# What are the things you want to run?
 # a. Things to run are defined in jobs
 # b. Where should we run the jobs? runs-on
 # c. what are the steps to run?

jobs:
  Deploy-our-lovely-artefact:
    runs-on: Ubuntu-latest #linux
    steps:
      - uses: actions/checkout@v4
      - name: create deploy folder
        run: mkdir for deploy folder
      - name: check system memory
        run: cp ec2_instance.tf deploy-folder/
        